In [2]:
import pandas as pd

df = pd.read_csv("C:/Titanic-Dataset.csv")

df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [3]:
print("DATASET INFORMATION")
df.info()

print("\nMISSING VALUES")
print(df.isnull().sum())

print("\nDUPLICATE ROWS")
print(df.duplicated().sum())

DATASET INFORMATION
<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

MISSING VALUES
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

DUPLICATE ROWS
0

In [4]:
df["Age"] = df["Age"].fillna(df["Age"].median())

print("Missing Age values:", df["Age"].isnull().sum())

Missing Age values: 0

In [5]:
# STEP 1: Handle missing values in Age

age_missing_before = df["Age"].isnull().sum()
age_median = df["Age"].median()

df["Age"] = df["Age"].fillna(age_median)

age_missing_after = df["Age"].isnull().sum()

print("Age missing values before cleaning :", age_missing_before)
print("Median age used for imputation     :", age_median)
print("Age missing values after cleaning  :", age_missing_after)

Age missing values before cleaning : 0
Median age used for imputation     : 28.0
Age missing values after cleaning  : 0

In [6]:
# STEP 2: Handle missing values in Cabin

cabin_missing_before = df["Cabin"].isnull().sum()

df["Cabin"] = df["Cabin"].fillna("Unknown")

cabin_missing_after = df["Cabin"].isnull().sum()

print("Cabin missing values before cleaning :", cabin_missing_before)
print("Cabin missing values after cleaning  :", cabin_missing_after)

Cabin missing values before cleaning : 687
Cabin missing values after cleaning  : 0

In [7]:
# STEP 3: Handle missing values in Embarked

embarked_missing_before = df["Embarked"].isnull().sum()
embarked_mode = df["Embarked"].mode()[0]

df["Embarked"] = df["Embarked"].fillna(embarked_mode)

embarked_missing_after = df["Embarked"].isnull().sum()

print("Embarked missing values before cleaning :", embarked_missing_before)
print("Mode used for imputation               :", embarked_mode)
print("Embarked missing values after cleaning  :", embarked_missing_after)

Embarked missing values before cleaning : 2
Mode used for imputation               : S
Embarked missing values after cleaning  : 0

In [8]:
# STEP 4: Check and remove duplicate rows

duplicates_before = df.duplicated().sum()

if duplicates_before > 0:
    df = df.drop_duplicates().reset_index(drop=True)

duplicates_after = df.duplicated().sum()

print("Duplicate rows before cleaning :", duplicates_before)
print("Duplicate rows after cleaning  :", duplicates_after)


# STEP 5: Standardize text columns

text_columns = df.select_dtypes(include="object").columns

for column in text_columns:
    df[column] = df[column].apply(
        lambda x: x.strip() if isinstance(x, str) else x
    )

print("\nText columns standardized:")
print(list(text_columns))

Duplicate rows before cleaning : 0
Duplicate rows after cleaning  : 0

Text columns standardized:
['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked']

C:\Users\HP\AppData\Local\Temp\ipykernel_29772\508808370.py:16: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_columns = df.select_dtypes(include="object").columns

In [9]:
# STEP 6: Validate and standardize data types

print("DATA TYPES BEFORE VALIDATION")
print(df.dtypes)

# Convert numerical columns to appropriate numeric types
numeric_columns = ["PassengerId", "Survived", "Pclass", "Age", "SibSp", "Parch", "Fare"]

for column in numeric_columns:
    df[column] = pd.to_numeric(df[column], errors="coerce")

# Convert categorical columns to string type
categorical_columns = ["Sex", "Cabin", "Embarked"]

for column in categorical_columns:
    df[column] = df[column].astype("string").str.strip()

print("\nDATA TYPES AFTER VALIDATION")
print(df.dtypes)

DATA TYPES BEFORE VALIDATION
PassengerId      int64
Survived         int64
Pclass           int64
Name               str
Sex                str
Age            float64
SibSp            int64
Parch            int64
Ticket             str
Fare           float64
Cabin              str
Embarked           str
dtype: object

DATA TYPES AFTER VALIDATION
PassengerId      int64
Survived         int64
Pclass           int64
Name               str
Sex             string
Age            float64
SibSp            int64
Parch            int64
Ticket             str
Fare           float64
Cabin           string
Embarked        string
dtype: object

In [10]:
# STEP 7: Final Data Quality Validation

print("=" * 50)
print("FINAL DATA QUALITY CHECK")
print("=" * 50)

print("\n1. Dataset Shape:")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

print("\n2. Missing Values:")
print(df.isnull().sum())

print("\n3. Total Missing Values:")
print(df.isnull().sum().sum())

print("\n4. Duplicate Rows:")
print(df.duplicated().sum())

print("\n5. Data Types:")
print(df.dtypes)

print("\n" + "=" * 50)
print("VALIDATION COMPLETED")
print("=" * 50)

==================================================
FINAL DATA QUALITY CHECK
==================================================

1. Dataset Shape:
Rows: 891
Columns: 12

2. Missing Values:
PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

3. Total Missing Values:
0

4. Duplicate Rows:
0

5. Data Types:
PassengerId      int64
Survived         int64
Pclass           int64
Name               str
Sex             string
Age            float64
SibSp            int64
Parch            int64
Ticket             str
Fare           float64
Cabin           string
Embarked        string
dtype: object

==================================================
VALIDATION COMPLETED
==================================================

In [11]:
# STEP 8: Export Cleaned Dataset

output_file = "Titanic-Cleaned.csv"

df.to_csv(output_file, index=False)

print("Cleaned dataset exported successfully!")
print("File name:", output_file)
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Cleaned dataset exported successfully!
File name: Titanic-Cleaned.csv
Rows: 891
Columns: 12

In [12]:
# STEP 9: Create Change Log

change_log = {
    "Issue": [
        "Missing values in Age",
        "Missing values in Cabin",
        "Missing values in Embarked",
        "Duplicate rows",
        "Text formatting",
        "Data type validation"
    ],
    
    "Before": [
        "177 missing values",
        "687 missing values",
        "2 missing values",
        "0 duplicate rows",
        "Potential leading/trailing spaces",
        "Validated original data types"
    ],
    
    "Action Taken": [
        "Filled missing values using median",
        "Filled missing values with 'Unknown'",
        "Filled missing values using mode",
        "Checked for duplicates; no removal required",
        "Removed leading/trailing spaces from text columns",
        "Validated numerical and categorical data types"
    ],
    
    "After": [
        "0 missing values",
        "0 missing values",
        "0 missing values",
        "0 duplicate rows",
        "Text values standardized",
        "Data types validated"
    ]
}

change_log_df = pd.DataFrame(change_log)

change_log_df

,Issue,Before,Action Taken,After
0,Missing values in Age,177 missing values,Filled missing values using median,0 missing values
1,Missing values in Cabin,687 missing values,Filled missing values with 'Unknown',0 missing values
2,Missing values in Embarked,2 missing values,Filled missing values using mode,0 missing values
3,Duplicate rows,0 duplicate rows,Checked for duplicates; no removal required,0 duplicate rows
4,Text formatting,Potential leading/trailing spaces,Removed leading/trailing spaces from text columns,Text values standardized
5,Data type validation,Validated original data types,Validated numerical and categorical data types,Data types validated

In [13]:
# STEP 10: Data Cleaning Summary / Write-up

write_up = """
DATA CLEANING AND PREPROCESSING REPORT
======================================

Dataset: Titanic Dataset
Original Size: 891 rows × 12 columns

1. MISSING VALUES - AGE
   Issue: 177 missing values were found in the Age column.
   Resolution: Missing Age values were replaced with the median Age.
   Result: 0 missing Age values remained.

2. MISSING VALUES - CABIN
   Issue: 687 missing values were found in the Cabin column.
   Resolution: Missing Cabin values were replaced with 'Unknown'
   to preserve the available records.
   Result: 0 missing Cabin values remained.

3. MISSING VALUES - EMBARKED
   Issue: 2 missing values were found in the Embarked column.
   Resolution: Missing values were replaced using the mode of the
   Embarked column.
   Result: 0 missing Embarked values remained.

4. DUPLICATE RECORDS
   Issue: Duplicate rows were checked.
   Resolution: No duplicate rows were found, so no records were removed.
   Result: 0 duplicate rows remained.

5. TEXT FORMATTING
   Issue: Text columns were checked for unnecessary leading or trailing spaces.
   Resolution: Leading and trailing spaces were removed from text columns.
   Result: Text values were standardized.

6. DATA TYPES
   Issue: Data types were validated for numerical and categorical columns.
   Resolution: Numerical columns were converted to appropriate numeric
   types and categorical columns were standardized as string values.
   Result: Data types were validated successfully.

FINAL VALIDATION
================
Rows: 891
Columns: 12
Total Missing Values: 0
Duplicate Rows: 0

Conclusion:
The dataset was cleaned and preprocessed successfully and is ready
for reliable data analysis.
"""

print(write_up)

DATA CLEANING AND PREPROCESSING REPORT
======================================

Dataset: Titanic Dataset
Original Size: 891 rows × 12 columns

1. MISSING VALUES - AGE
   Issue: 177 missing values were found in the Age column.
   Resolution: Missing Age values were replaced with the median Age.
   Result: 0 missing Age values remained.

2. MISSING VALUES - CABIN
   Issue: 687 missing values were found in the Cabin column.
   Resolution: Missing Cabin values were replaced with 'Unknown'
   to preserve the available records.
   Result: 0 missing Cabin values remained.

3. MISSING VALUES - EMBARKED
   Issue: 2 missing values were found in the Embarked column.
   Resolution: Missing values were replaced using the mode of the
   Embarked column.
   Result: 0 missing Embarked values remained.

4. DUPLICATE RECORDS
   Issue: Duplicate rows were checked.
   Resolution: No duplicate rows were found, so no records were removed.
   Result: 0 duplicate rows remained.

5. TEXT FORMATTING
   Issue: Text columns were checked for unnecessary leading or trailing spaces.
   Resolution: Leading and trailing spaces were removed from text columns.
   Result: Text values were standardized.

6. DATA TYPES
   Issue: Data types were validated for numerical and categorical columns.
   Resolution: Numerical columns were converted to appropriate numeric
   types and categorical columns were standardized as string values.
   Result: Data types were validated successfully.

FINAL VALIDATION
================
Rows: 891
Columns: 12
Total Missing Values: 0
Duplicate Rows: 0

Conclusion:
The dataset was cleaned and preprocessed successfully and is ready
for reliable data analysis.

In [14]:
# STEP 11: Export Change Log

change_log_file = "Titanic-Change-Log.csv"

change_log_df.to_csv(change_log_file, index=False)

print("Change log exported successfully!")
print("File name:", change_log_file)

Change log exported successfully!
File name: Titanic-Change-Log.csv

In [15]:
# STEP 12: Final File Verification

import os

files_to_check = [
    "Titanic-Cleaned.csv",
    "Titanic-Change-Log.csv"
]

print("FINAL FILE VERIFICATION")
print("=" * 40)

for file in files_to_check:
    if os.path.exists(file):
        print(f"✓ {file} - READY")
    else:
        print(f"✗ {file} - NOT FOUND")

print("\nCleaned Dataset Shape:", df.shape)
print("Total Missing Values:", df.isnull().sum().sum())
print("Duplicate Rows:", df.duplicated().sum())

FINAL FILE VERIFICATION
========================================
✓ Titanic-Cleaned.csv - READY
✓ Titanic-Change-Log.csv - READY

Cleaned Dataset Shape: (891, 12)
Total Missing Values: 0
Duplicate Rows: 0